### ISSUE TITLE
handle 503 timeouts

### ISSUE THREAD

**Issue by displague** [akerl/linodeapi#17]
https://github.com/akerl/linodeapi/blob/master/lib/linodeapi/raw.rb#L75

```
undefined method `reject!' for nil:NilClass

/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.0/lib/linodeapi/raw.rb:75:in `parse'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.0/lib/linodeapi/raw.rb:71:in `call'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.0/lib/linodeapi/raw.rb:62:in `block in make_call'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.0/lib/linodeapi/raw.rb:63:in `make_call'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.0/lib/linodeapi/raw.rb:44:in `method_missing'
/Users/marques/.vagrant.d/gems/gems/vagrant-linode-0.1.2/lib/vagrant-linode/actions/create.rb:33:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

While trying to reproduce, https://github.com/displague/vagrant-linode/issues/34, I used the following Vagrantfile and command to run into the error above:
```vagrant up --parallel --provision```
```ruby
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	['newark','dallas','fremont','atlanta'].each do |datacenter|
	  (1..4).each do |i|
		['dev','prod'].each do |linode_env|
			config.vm.define "#{linode_env}#{i}-#{datacenter}" do |linode|
				linode.vm.synced_folder ".", "/vagrant", rsync__exclude: [".git/",'vendor/'], type: 'rsync'
				linode.vm.hostname = "#{linode_env}#{i}-#{datacenter}"
				linode.vm.provider :linode do |provider, override|
					override.ssh.private_key_path = '~/.ssh/id_rsa'
					override.vm.box = "linode"
					override.vm.box_url = "https://github.com/displague/vagrant-linode/raw/master/box/linode.box"

					provider.kernel = '4.0.5'
					provider.label = linode.vm.hostname
					provider.token = ENV['LINODE_API_KEY'] 
					provider.datacenter = datacenter
					provider.plan = 'Linode 1024'
					provider.distribution = 'Debian 8'
				end
			end
		end
  	  end
	end
end
```

**Comment by akerl** [comment]
It's failing here because the value of resp['ERRORARRAY'] is nil. I could theoretically handle that, but given that ERRORARRAY is supposed to always be provided, that seems less than ideal.

I'd be curious to see the raw API response for that call, given that hitting a server-side limit should be throwing an error code and thus causing ERRORARRAY to contain something

**Comment by displague** [comment]
Adding `p resp`, reveals:

```
<html>\r\n<head><title>503 Service Temporarily Unavailable</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>503 Service Temporarily
                Unavailable</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n
```

**Comment by akerl** [comment]
Added a change to catch non-200 response codes or nil response bodies and raise more clear error messages to the user.

Also opened a branch to get some cleaner logging available via LINODEAPI_DEBUG=1 or passing debug: true as a parameter, but I'd like to do the output "Right", which will take a bit more work

**Comment by akerl** [comment]
0.1.1 released with the fixes. can you confirm they make the error message a bit more sane?

**Comment by displague** [comment]
Looks sane, thanks!

```
An unexpected error occurred when executing the action on the
'dev4-atlanta' machine. Please report this as a bug:

API threw HTTP error code 503

/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:76:in `error_check'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:71:in `call'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:62:in `block in make_call'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:63:in `make_call'
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:44:in `method_missing'
/Users/marques/.vagrant.d/gems/gems/vagrant-linode-0.1.2/lib/vagrant-linode/actions/create.rb:33:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```
